parameters:
#    jam_storage.example.class: Kinash\JamStorageBundle\Example

services:
    sonata.clone.service:
        class: Kinash\JamStorageBundle\Service\CloneService
        arguments: [ @doctrine.orm.entity_manager]
#    jam_storage.example:
#        class: %jam_storage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
