parameters:
#    jam_storage.example.class: Kinash\JamStorageBundle\Example


services:
    jamjar.clone.factory:
        class: Kinash\JamStorageBundle\Classes\CloneFactory
    jamjar.clone.service:
        class: Kinash\JamStorageBundle\Service\CloneService
        arguments: [ @doctrine.orm.entity_manager,@jamjar.clone.factory]
